version: 2.1
jobs:
  check-whitespace:
    docker:
      - image: debian:jessie-20190228-slim
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: dev-scripts/check-trailing-whitespace
  build:
    docker:
      - image: peaceiris/hugo:v0.119.0
    steps:
      - checkout
      - run:
          name: Get submodules
          command: |
            git submodule init
            git submodule update --remote
      - attach_workspace:
          at: ./
      - run:
          name: Build prod site
          command: hugo version && hugo
      - persist_to_workspace:
          root: ./
          paths:
            - public
            - tests
  publish_draft:
    docker:
      - image: cimg/node:14.18.1
    environment:
      NETLIFY_SITE_ID: efdd3190-2d13-4eb8-8dcf-d5e77f21af28
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      # This is a hack to get rid of the <base> tag, which prevents the blog from rendering
      # properly on Netlify's draft URL because it hardcodes the mtlynch.io domain.
      - run:
          name: Remove base tag from generated HTML
          command: find public -name "*.html" -exec sed -i -e 's/<base[^>]*>//g' {} +
      - run:
          name: Install netlify CLI
          command: npm install netlify-cli --save-dev
      - run:
          name: Deploy a live draft
          command: ./node_modules/.bin/netlify deploy --dir=public --site="${NETLIFY_SITE_ID}"
  deploy:
    docker:
      - image: cimg/node:14.18.1
    environment:
      NETLIFY_SITE_ID: efdd3190-2d13-4eb8-8dcf-d5e77f21af28
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install netlify CLI
          command: npm install netlify-cli --save-dev
      - run:
          name: Deploy to production
          command: ./node_modules/.bin/netlify deploy --dir=public --site="${NETLIFY_SITE_ID}" --prod
workflows:
  version: 2
  test-deploy:
    jobs:
      - check-whitespace
      - build
      - publish_draft:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - check-whitespace
            - build
          filters:
            branches:
              only: master
